### PR TITLE
add dman to frontpage

### PR DESCRIPTION
**Pull request by wilzbach**
- adds dman to the frontpage (different position based on device width)
- simplifies "wall of text" to bullet points (not perfect yet)
- cuts also text in "About the tour"
- uses __bold__ instead of _italic_ for the introduction sentence.

This is a WIP-PR and the bullet points about D need still some work.

desktop:

image

mobile:

image

We also need to figure out the best way to have such visual improvements without making the translation problematic.

tries to fix: #237

### CODE REVIEW

**Comment by stonemaster** [comment]
Is there a possibility to omit having HTML inside the content? I really would like to avoid having styling and content mixed because it makes translation later and maintenance harder in the long run..

**Comment by wilzbach** [comment]
> Is there a possibility to omit having HTML inside the content? I really would like to avoid having styling and content mixed because it makes translation later and maintenance harder in the long run..

I fully agree with you and imho the best way to go is to have some kind of macros/templates that expand to HTML or alternatively if needed only take the translated strings as input - see #55

**Comment by wilzbach** [comment]
btw I found this the dancing [DMan](http://bl.ocks.org/amamama/raw/1ca18244e4e298ace6ff/) online and when you put it into a loop - it's quite funny:
https://codepen.io/greenify/full/oLLbzR/

**Comment by stonemaster** [comment]
👍 for the bullet list. The introduction was getting too long and that is much more concise now.

What I don't like about the image is the mixing with HTML code. Maybe we should wait here for #55. 
And - although being official - the icon looks a little bit like kindergarden :P
I can't really estimate how that looks like for new users but I just don't want users to think about D as a toy language.

**Comment by wilzbach** [comment]
> What I don't like about the image is the mixing with HTML code. Maybe we should wait here for #55. 

Okay this PR now only contains the D-Man ;-)

> I can't really estimate how that looks like for new users but I just don't want users to think about D as a toy language.

That's a very valid concern! I loved the logo from [DConf 2016](http://dconf.org/2016/index.html).
Maybe @leandro-lucarella-sociomantic know whether we could use that for the front page of the tour?

**Comment by leandro-lucarella-sociomantic** [comment]
> That's a very valid concern! I loved the logo from DConf 2016.
> Maybe @leandro-lucarella-sociomantic know whether we could use that for the front page of the tour?

We tried to convince @WalterBright and @andralex to give dlang's some new life but they had some concerns (specially Walter). The logos done for DConf are of course available to be used for whatever you want, but I would ask for a blessing from Walter and Andrei. If you need them in any particular format let me know (I guess Walter/Andrei should have the "sources" too).

**Comment by leandro-lucarella-sociomantic** [comment]
BTW, I also think as cute as the D man is, it gives the language a toy feeling... But then there you have the go gopher (which I also don't particularly like because of the same reason :P)

**Comment by WalterBright** [comment]
I'm fine with either the D-Man or the DConf logo.

**Comment by andralex** [comment]
I suggest we phase the D-Man out.

**Comment by CyberShadow** [comment]
> I suggest we phase the D-Man out.

Rationale?

I don't think being a little whimsical is hurting us. It's not unusual, see e.g. https://phacility.com/phabricator/.

I don't think Go's mascot is hurting them either.

At this point D-Man is well associated with the language, and there is some amount of "pop culture" to go with it, see e.g. https://twitter.com/DlangGuy. I know this is terribly unscientific but perhaps a little embodied personality wouldn't hurt.

**Comment by wilzbach** [comment]
Let me quickly give some motivation for this.

We observed that our drop-out rate at the frontpage is 37% (#233), so the idea was to add visual elements to lure the reader into the Tour ;-)

Why the D Mascot?
--------------------------

and as already mentioned the Golang Tour presents their "Gopher" too ...

image

https://tour.golang.org

> here is some amount of "pop culture" to go with it, see e.g. https://twitter.com/DlangGuy. I know this is terribly unscientific but perhaps a little embodied personality wouldn't hurt.

You should definitely mention the [work](https://twitter.com/simd_nyan) of @simdnyan too, e.g.:

image

**Comment by WalterBright** [comment]
Looks like I'm following DlangGuy now!

**Comment by leandro-lucarella-sociomantic** [comment]
LOL. I also have a completely new perspective on the D-Man now! :joy:

**Comment by WalterBright** [comment]
Rebase, and then merge!

**Comment by stonemaster** [comment]
If @WalterBright says it everything else is overruled :-) 👍

**Comment by wilzbach** [comment]
>> Rebase, and then merge!
> If @WalterBright says it everything else is overruled :-)

D-Man Canon is loaded and ready to fire!

**Pull request merged**
