### PR TITLE
Add C memory management example to Slices section

### PR DESCRIPTION
**Pull request by JackStouffer**
I don't know if this is too advanced for this section and you want it somewhere else, but this is a really cool feature of D. Also, it seems a lot of D regulars didn't even know about this feature: https://forum.dlang.org/post/mdnslsswqwxaugbaifaj@forum.dlang.org

### CODE REVIEW

**Comment by wilzbach** [comment]
I really like this feature (I didn't know about it before), so yes it should be documented, but I am not sure whether the basic tour is the right place. Maybe we can have a new gem for (advanced) manual memory management. It Could then also be extended to cover the Allocator api? 
See also #159

**Comment by stonemaster** [comment]
I like this feature too. But I share @wilzbach's opinion about this feature being mentioned in the basic feature. D is a very sophisticated language and so the basic section is much more advanced already than that one of e.g. Go. I think we should make sure not to introduce too much special features here to make sure readers stay until the gems section. I like the about a gem on memory allocation where this feature is shown.

**Comment by ZombineDev** [comment]
I think a dedicated section about systems programming concepts is needed. Very often people on the forums mention that they come from scripting/high-level languages and are not sure where to start. Also people comming from C/C++ we feel right at home. Here's a nice crowd-sourced book: https://github.com/angrave/SystemProgramming/wiki

Another option is to have something like "Effective D" where advanced concepts would be used in a more organized way. E.g. a series API or algorithm design problems, where first a naive Java-like solution is presented and then an idiomatic D solution which ties several Gems together, followed by a short discussion on why D's approach is better. For example using UDAs + CT introspection + static if for implementing (de)serialization.

**Comment by JackStouffer** [comment]
I'm going to start small with a section in the gems area. I think we could either expand it later to a full blown "Systems Level D for ~~Script Kiddies~~ JavaScript Users" (lol), or a link to an external resource.

**Comment by stonemaster** [comment]
Closing due to discussion.

**Comment by wilzbach** [comment]
@JackStouffer can you resubmit with a new gem on systems programming?

**Comment by JackStouffer** [comment]
Systems programming, isn't my strong suit. I'd be happy to submit one for manual memory management with std.allocator and malloc/slices, that is if I ever find the time ;)

**Pull request closed without merging**
