### PR TITLE
RESUBMISSION: 	Use static assert for pointer types

### PR DESCRIPTION
**Pull request by wilzbach**
#89 - do not merge

### CODE REVIEW

**Comment by stonemaster** [comment]
Please rebase a last time to allow source code checking to kick in as per #57 :-)

**Comment by wilzbach** [comment]
rebased.

**Comment by wilzbach** [comment]
This was failing due to the increased width, reformatted & rebased.

**Comment by stonemaster** [comment]
Reopen because compilation container was fixed.

**Comment by wilzbach** [comment]
From https://dlang.org/spec/traits.html:

"Returns a bool true if all of the arguments compile (are semantically correct). The arguments can be symbols, types, or expressions that are syntactically correct. The arguments cannot be statements or declarations."

So well I guess we can't do this with `__traits(compiles, ...)`, I opened an [enhancement request](https://issues.dlang.org/show_bug.cgi?id=16175) - maybe this gets fixed at some point :)

**Pull request closed without merging**
