### PR TITLE
word change: online  -> interactive

### PR DESCRIPTION
**Pull request by wilzbach**

### CODE REVIEW

**Comment by ZombineDev** [comment]
LGTM

**Comment by wilzbach** [comment]
@stonemaster: As we are atm a bit in the lack of reviewers and it's a simple one word change I went directly ahead and merged.

**Comment by stonemaster** [comment]
:+1: perfect thanks!

Am 13.08.2016 14:40 schrieb "Sebastian Wilzbach" <notifications@github.com>:
>
> @stonemaster: As we are atm a bit in the lack of reviewers and it's a
simple one word change I went directly ahead and merged.

**Comment by wilzbach** [comment]
> :+1: perfect thanks!

btw @stonemaster how about giving @ZombineDev also merge access? We require the CI to pass anyways and have force-push protection ;-)

**Comment by stonemaster** [comment]
I am fine with that. Currently travelling, do you habe the rights to do
that? Otherwise I'll do tonight. Will also reply later to to other great
@ZombineDev thread!

Am 13.08.2016 14:48 schrieb "Sebastian Wilzbach" <notifications@github.com>:

**Comment by wilzbach** [comment]
> I am fine with that. Currently travelling, do you habe the rights to do
that? Otherwise I'll do tonight. 

Great & I don't have the permissions to do so.
Btw if you are already in the web-interface you might want to define a new milestone for sth. like 1.1 into which imho at least these two issues fall:
- dub (#29)
- menu bar at left (#52)

**Comment by stonemaster** [comment]
:+1: will do

Am 13.08.2016 14:54 schrieb "Sebastian Wilzbach" <notifications@github.com>:

**Comment by ZombineDev** [comment]
> stonemaster invited you to stonemaster/dlang-tour

@stonemaster @wilzbach Thanks guys! I feel honored!

**Pull request merged**
