### PR TITLE
use table for basic types

### PR DESCRIPTION
**Pull request by wilzbach**
Not ideal, but at least a bit nicer representation of basic types.

### CODE REVIEW

**Comment by stonemaster** [comment]
Did you check whether this actually works with the markdown parser of vibe.d?

**Comment by wilzbach** [comment]
image

**Comment by stonemaster** [comment]
Great. Didn't that feature. The "markdown" looks ugly but the final result looks good.

**Comment by wilzbach** [comment]
Yes you can have arbitrary HTML within markdown, but of course you can't have markdown once a HTML tree was started ;-)

**Pull request merged**
