### PR TITLE
change spelling of Mac OS and add it to the script installer list

### PR DESCRIPTION
**Pull request by wilzbach**
CC @jacob-carlborg 

AFAIK this is the common spelling nowadays?

### CODE REVIEW

**Comment by vladdeSV** [comment]
I've always referred to it as 'OS X'

**Comment by jacob-carlborg** [comment]
Apple changed the name of the OS when they announced the latest version, Sierra. Apparently it did line up properly on their slides with the rest of the OS names, iOS, tvOS watchOS 😃.

**Comment by vladdeSV** [comment]
Then we'll go with that!

**Comment by vladdeSV** [comment]
Wikipedia states "[[...] was originally branded "Mac OS X", renamed to "OS X" in 2012,[4] and announced to be renamed to "macOS" in the upcoming version in 2016.](https://www.wikiwand.com/en/Mac_OS)"

**Comment by jacob-carlborg** [comment]
The circle is now complete. It's back to the original name Mac OS, the name used before Mac OS X. Which really is not the same OS, which adds to the confusion.

**Pull request merged**
