### PR TITLE
use the official dlang menu

### PR DESCRIPTION
**Pull request by wilzbach**
uses the official dlang menu css/js. I left the search css classes in there, in case we want to add a search?

before:

image

image

after:

image

image

### CODE REVIEW

**Comment by wilzbach** [comment]
fixes #42

**Comment by wilzbach** [comment]
@stonemaster what is your opinion on moving forward to the official D theme?

**Comment by stonemaster** [comment]
I am okay with that, I just didn't have a chance to look at the pull unfortunately... I just want to make sure bootstrap which is used in the rest of the page doesn't infer with any other changes related to the official dlang theme. And some redundancies might need to be removed (like custom bootstrap nav theming).

**Comment by stonemaster** [comment]
I tried it out locally and it looks good.
Could you just remove everything belong to /** Navbar customization **/ in `static/css/common.css`? This was a bootstrap color scheme customization and is now redundant (everything from the comment until the end of the file). Thanks.

**Comment by wilzbach** [comment]
> Could you just remove everything belong to /** Navbar customization **/ in static/css/common.css? This was a bootstrap color scheme customization and is now redundant (everything from the comment until the end of the file). Thanks.

Done and also moved the menu customization from `tour.css` to `common.css` ;-)

**Comment by stonemaster** [comment]
Perfect. So let's roll :-)

**Pull request merged**
