### PR TITLE
Fix compilation with DMD 2.072.0

### PR DESCRIPTION
**Pull request by ZombineDev**
As mentioned in https://github.com/stonemaster/dlang-tour/pull/471#issuecomment-258311882,  [D:YAML](https://github.com/kiith-sa/D-YAML) doesn't build with DMD 2.072.0. I fixed the compilation problems, and opened a [PR](https://github.com/kiith-sa/D-YAML/pull/49), but in the meantime, I wanted to fix our CI, so I [forked](https://github.com/dlang-tour/dyaml-dlang-tour) the project and registered it at [code.dlang.org](http://code.dlang.org/packages/dyaml-dlang-tour).

Finally, this PR makes dlang-tour use the forked package which should fix our CI.

### CODE REVIEW

**Comment by ZombineDev** [comment]
It looks like I need to fix a couple of other issues as well: 
* [ ] Fix [mustache-d](https://github.com/repeatedly/mustache-d/pull/28) compilation with DMD 2.072.0
* [ ] Upgrade to vibe.d 0.7.30 to enable building dlang-tour with 2.072.0

**Comment by wilzbach** [comment]
Omg - the 2.072 release really broke a lot :/
Thanks a lot for your hard efforts!!

**Comment by ZombineDev** [comment]
I decided to speed things up and did the fork-and-fix thing with [mustache-d](https://github.com/dlang-tour/mustache-d-dlang-tour) as well. I'm not a fan of forking libraries, but for libraries that are not actively developed it may be the only way to ensure quick fixes and overall project stability.

**Comment by ZombineDev** [comment]
I also fixed a couple deprecation messages caused by DMD 2.071. With all that out of the way, I think this PR is ready.

**Comment by wilzbach** [comment]
Thanks a lot again :)

**Pull request merged**
