### PR TITLE
Revert "remove some of the incomplete sections"

### PR DESCRIPTION
**Pull request by stonemaster**
Reverts stonemaster/dlang-tour#203

Sanity check fails

### CODE REVIEW

**Comment by wilzbach** [comment]
How about directly fixing the error than reverting? 
I mean also reverting takes time ;-)

**Comment by stonemaster** [comment]
I currently don't have access to a computer just a pad :-) but these sections should really not compile because there are to be competed by the user..

**Comment by wilzbach** [comment]
> these sections should really not compile because there are to be competed by the user..

They should because otherwise we get frustrated newbie  users ;-)

**Comment by stonemaster** [comment]
That's another topic. Currently the sanity check fails. And some how we need something incomplete to validate that the exercise has been done right :-)

**Pull request merged**
