### PR TITLE
[Issue #235] Simplify welcome page four

### PR DESCRIPTION
**Pull request by JackStouffer**
screen shot 2016-06-10 at 2 55 58 pm

Welcome page four has the biggest drop off of any page other than the home page. This should reduce the "too much information" feeling that some might get.

### CODE REVIEW

**Comment by wilzbach** [comment]
Nice that should hopefully fix #235 :)

**Comment by ZombineDev** [comment]
LGTM content-wise. It would be nice if we had something like dlang.org's AutoTester, so reviewers could see what users will after PRs are merged.

**Comment by wilzbach** [comment]
>  It would be nice if we had something like dlang.org's AutoTester, so reviewers could see what users will after PRs are merged.

I hope that in the future with the upcoming single file change  just the markdown preview of Github will work for most. 

@stonemaster: can I start to merge such trivial additions? :)

**Comment by stonemaster** [comment]
@wilzbach please proceed :-) had a quick look too and everything's looks good.

**Comment by wilzbach** [comment]
Let's go then! Thanks @JackStouffer!

**Pull request merged**
