### PR TITLE
mention install script

### PR DESCRIPTION
**Pull request by MartinNowak**
- a good alternative on any unix system to quickly get started and try out different compilers

### CODE REVIEW

**Comment by wilzbach** [comment]
LGTM, btw @MartinNowak did you have time to map `install.dlang.io` and `i.dlang.io` to this script?
The idea is that the lazy people (like me) can then do `curl i.dlang.io | bash`

**Comment by MartinNowak** [comment]
> LGTM, btw @MartinNowak did you have time to map install.dlang.io and i.dlang.io to this script?
> The idea is that the lazy people (like me) can then do curl i.dlang.io | bash

On second thought (after dconf) I concluded this wasn't such a good idea. Executing a remote script requires quite some security measures. This is currently powered by dlang.org's certificate to provide authentication and by me signing the script (https://dlang.org/install.sh.sig) and downloads so the can be checked against https://dlang.org/gpg_keys.html or https://dlang.org/d-keyring.gpg.

**Comment by MartinNowak** [comment]
Once you've installed the script you can also run `~/dlang/install.sh dmd-beta`.

**Comment by stonemaster** [comment]
Thanks a lot!

**Pull request merged**
