### PR TITLE
restructure run locally + add documentation links

### PR DESCRIPTION
**Pull request by wilzbach**
Idea: using either dmd or rdmd is the first command that a newcomer should need to execute.

### CODE REVIEW

**Comment by wilzbach** [comment]
what does this error mean?

```
object.Exception@source/contentprovider.d(101): public/content/en/welcome.md: Just one empty chapter title allowed: Run D program locally
```

I thought I can have subsections?

**Comment by wilzbach** [comment]
> what does this error mean?

Ah I should read error messages, apparently it's bad to have 

```
# Chapter

#### A headline
```

because that's treated as "an empty chapter". Now I just put a small introduction sentence in here, maybe it's even good to have this requirement ;-)

**Comment by stonemaster** [comment]
Yeah the first 1st level section title is taken as the title for the whole chapter. That's something to keep in in mind for #137 btw..

**Comment by stonemaster** [comment]
Reopen because compilation container was fixed.

**Comment by wilzbach** [comment]
> Reopen because compilation container was fixed.

Rebased & CI is passing now :)

**Pull request merged**
