### PR TITLE
deleted unnecessary "in"

### PR DESCRIPTION
**Pull request by dmi7ry**
`Object class in  in Programming in D` -> `Object class in Programming in D`

### CODE REVIEW

**Comment by wilzbach** [comment]
@dmi7ry good catch!

Unfortunately I am not an admin and this project has [status checks enabled](https://help.github.com/articles/about-required-status-checks/) so I can only merge if the latest change pass on Travis. We will figure out a better solution (@audience - ideas?) once @stonemaster is back, but for now I would be very happy if you could either rebase this PR or resubmit it (probably faster).

**Comment by JackStouffer** [comment]
Travis isn't the problem here. @dmi7ry you need to rebase your branch on `master`

```
git rebase origin/master
```

**Comment by dmi7ry** [comment]
ok, will be done

**Comment by dmi7ry** [comment]
git not loves me. I losing many time. If I'll close this PR and do this fix for last version of the file (as I see, previous PR already merged), will be it ok?

**Comment by wilzbach** [comment]
Sure sorry about the inconveniences :/

**Pull request closed without merging**
