### PR TITLE
mark dub as executable with backticks

### PR DESCRIPTION
**Pull request by wilzbach**

### CODE REVIEW

**Comment by ZombineDev** [comment]
Before:

dlang-tour_pull_407_before

After:

dlang-tour_pull_407_after

LGTM!

**Comment by ZombineDev** [comment]
I'll go ahead and merge since the change is simple and I have verified locally that it works.

**Comment by wilzbach** [comment]
> I'll go ahead and merge since the change is simple and I have verified locally that it works.

Thanks, but for such trivial changes there is really no need to verify it locally..in case you want a markdown preview, you may click on the view tab - that should be easier and more convenient ;-)

**Comment by ZombineDev** [comment]
Yeah I know. I just didn't want to screw up just after I was promoted to a contributor :D + it was an excuse for me get hands on with the code ;)

**Comment by wilzbach** [comment]
> Yeah I know. I just didn't want to screw up just after I was promoted to a contributor :D

I was just worried that you spend more time on the PR than it took me to create & submit ;-)

**Pull request merged**
