### PR TITLE
typo: a -> e

### PR DESCRIPTION
**Pull request by wilzbach**

### CODE REVIEW

**Comment by ZombineDev** [comment]
LGTM. I've just rebased the branch, so I'll wait for the CI and then I'll merge.

**Comment by ZombineDev** [comment]
BTW @wilzbach is it ok if I delete branches like [wilzbach-patch-8](https://github.com/stonemaster/dlang-tour/tree/wilzbach-patch-8) after the corresponding PR has been merged?

**Comment by wilzbach** [comment]
> BTW @wilzbach is it ok if I delete branches like wilzbach-patch-8 after the corresponding PR has been merged?

Yes of course ;-)
(but I do regular cleanups anyways in case you forget)

FYI: those are automatically generated by Github when editing the file through the web UI. Unfortunately I can't tell them without much effort that the branch should be created on my own fork.

**Comment by ZombineDev** [comment]
> FYI: those are automatically generated by Github when editing the file through the web UI. Unfortunately I can't tell them without much effort that the branch should be created on my own fork.

Yeah, I know. I'm asking just in case.

**Pull request merged**
