### PR TITLE
Make type-safety sound more positive

### PR DESCRIPTION
**Pull request by markuslaker**
`Limitations' sounds as if we're stopping programmers from doing things.  Let's, instead, talk about the support that type-safety gives developers to build things they couldn't have built without it.  This, to me, is one of D's biggest advantages over more dynamic languages, such as Perl or Ruby.

### CODE REVIEW

**Comment by wilzbach** [comment]
Don't forget to mention there is this huge project typescript which tries to get types into Javascript. LGTM. Thanks for helping out and making the D tour better :)

**Comment by markuslaker** [comment]
You're more than welcome.  This tour is a great idea, and you've done
excellent work here.  But I need to break off soon: it's 12:30am here in
the UK.

BTW, in the last three minutes, the sample code at <
http://tour.dlang.org/tour/basics/6> has gone missing.

M.

**Comment by markuslaker** [comment]
I'm sorry, please ignore that last sentence.  The fault was at my end, not
yours.

M.

**Comment by wilzbach** [comment]
> This tour is a great idea, and you've done excellent work here. 

Wasn't me - full credit goes to @stonemaster

**Comment by stonemaster** [comment]
Thanks again.

**Pull request merged**
